services:
  api:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongo
    command: ['./wait-for-it.sh', 'mongo:27017', '--', 'npm', 'start'] # Wait until MongoDB is ready

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
